#................................................
# De funciones.pu traer ñas funciones suma y promedio
#................................................
from funciones import suma,promedio
print(suma(100,200))
print(promedio(100,200))
